services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: streamhive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: parth@7677
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
      - kafka

  celery_worker:
    build: .
    command: celery -A backend worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

  consumer_logging:
    build: .
    command: python manage.py start_logging_consumer
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - kafka
      - db

  consumer_notification:
    build: .
    command: python manage.py start_notification_consumer
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - kafka
      - db

volumes:
  postgres_data: