# Generated by Django 4.2.30 on 2026-04-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
