# Generated by Django 4.2.30 on 2026-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_verificationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationrequest",
            name="reason",
            field=models.TextField(max_length=500),
        ),
    ]
