# Generated by Django 4.2.30 on 2026-05-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_passwordresetotp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="block",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="passwordresetotp",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
