# Generated by Django 4.2.30 on 2026-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_create_at_block_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetotp",
            name="reset_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="reset_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
