# Generated by Django 4.2.30 on 2026-05-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_passwordresetotp_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="email", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="auth_provider_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["auth_provider", "auth_provider_id"],
                name="users_auth_pr_b4d5b4_idx",
            ),
        ),
    ]
