class Topics:
    POST_CREATED = "post.created"
    POST_LIKED = "post.liked"
    POST_UNLIKED = "post.unliked"
    POST_COMMENTED = "post.commented"
    POST_REPOSTED = "post.reposted"
    USER_FOLLOWED = "user.followed"
    USER_UNFOLLOWED = "user.unfollowed"
    USER_MENTIONED = "user.mentioned"
    VERIFICATION_APPROVED = "verification.approved"
    VERIFICATION_REJECTED = "verification.rejected"