# Generated by Django 4.2.30 on 2026-07-01 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0004_post_is_pinned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "collections",
            },
        ),
        migrations.CreateModel(
            name="CollectionPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="posts.collection",
                    ),
                ),
            ],
            options={
                "db_table": "collection_posts",
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="saved_count",
        ),
        migrations.DeleteModel(
            name="SavedPost",
        ),
        migrations.AddField(
            model_name="collectionpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="posts",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="posts.CollectionPost",
                to="posts.post",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionpost",
            index=models.Index(
                fields=["collection"], name="collection__collect_687111_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionpost",
            index=models.Index(fields=["post"], name="collection__post_id_da884a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="collectionpost",
            unique_together={("collection", "post")},
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["owner"], name="collections_owner_i_ccfa6d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("owner", "name")},
        ),
    ]
