# Generated by Django 4.2.30 on 2026-07-01 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0005_collection_collectionpost_remove_post_saved_count_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="collection",
            name="collections_owner_i_ccfa6d_idx",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="owner",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("author", "name")},
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["author"], name="collections_author__a05e0f_idx"
            ),
        ),
    ]
