# Generated by Django 4.2.30 on 2026-05-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_rename_notifications_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("repost", "Repost"),
                    ("mention", "Mention"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
