# Generated by Django 4.2.30 on 2026-06-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("repost", "Repost"),
                    ("mention", "Mention"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("comment_like", "Comment Like"),
                ],
                max_length=20,
            ),
        ),
    ]
